import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

const variant = v.object({
  sku: v.string(),
  strength: v.string(),
  price: v.number(),
  inventory: v.number(),
  lowStockAt: v.number(),
  active: v.boolean(),
});

export default defineSchema({
  ...authTables,
  adminUsers: defineTable({
    userId: v.id("users"),
    role: v.union(v.literal("owner"), v.literal("manager")),
    displayName: v.optional(v.string()),
    phone: v.optional(v.string()),
    emailNotifications: v.optional(v.boolean()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  products: defineTable({
    slug: v.string(),
    name: v.string(),
    category: v.union(v.literal("GLP-1"), v.literal("Peptides")),
    description: v.string(),
    image: v.string(),
    badge: v.optional(v.string()),
    featured: v.optional(v.boolean()),
    tags: v.optional(v.array(v.string())),
    seoTitle: v.optional(v.string()),
    seoDescription: v.optional(v.string()),
    sortOrder: v.optional(v.number()),
    active: v.boolean(),
    variants: v.array(variant),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_active", ["active"]),
  customers: defineTable({
    email: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    phone: v.optional(v.string()),
    orderCount: v.number(),
    lifetimeValue: v.number(),
    notes: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_email", ["email"]),
  orders: defineTable({
    orderNumber: v.string(),
    customerEmail: v.string(),
    customerName: v.string(),
    status: v.union(v.literal("draft"), v.literal("pending"), v.literal("paid"), v.literal("fulfilled"), v.literal("cancelled"), v.literal("refunded")),
    paymentStatus: v.union(v.literal("unpaid"), v.literal("processing"), v.literal("paid"), v.literal("refunded")),
    items: v.array(v.object({ sku: v.string(), name: v.string(), strength: v.string(), quantity: v.number(), unitPrice: v.number() })),
    subtotal: v.number(),
    discount: v.number(),
    shipping: v.number(),
    total: v.number(),
    shippingAddress: v.object({ line1: v.string(), line2: v.optional(v.string()), city: v.string(), state: v.string(), postalCode: v.string(), country: v.string() }),
    notes: v.optional(v.string()),
    checkoutToken: v.optional(v.string()),
    shippingMethodName: v.optional(v.string()),
    trackingNumber: v.optional(v.string()),
    internalNotes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_order_number", ["orderNumber"]).index("by_created_at", ["createdAt"]),
  discounts: defineTable({
    code: v.string(),
    type: v.union(v.literal("percent"), v.literal("fixed")),
    amount: v.number(),
    active: v.boolean(),
    usageCount: v.number(),
    startsAt: v.number(),
    endsAt: v.optional(v.number()),
  }).index("by_code", ["code"]),
  batches: defineTable({
    productSlug: v.string(),
    compound: v.string(),
    lotNumber: v.string(),
    certificateUrl: v.string(),
    testedAt: v.number(),
    published: v.boolean(),
  }).index("by_product", ["productSlug"]).index("by_lot", ["lotNumber"]),
  storeSettings: defineTable({
    singleton: v.string(),
    storeName: v.string(),
    supportEmail: v.optional(v.string()),
    supportPhone: v.optional(v.string()),
    legalName: v.optional(v.string()),
    freeShippingThreshold: v.number(),
    minimumOrder: v.number(),
    checkoutEnabled: v.boolean(),
    announcement: v.string(),
    storeTagline: v.optional(v.string()),
    contactAddress: v.optional(v.string()),
    currency: v.optional(v.string()),
    timezone: v.optional(v.string()),
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    darkLogoUrl: v.optional(v.string()),
    faviconUrl: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_singleton", ["singleton"]),
  storeDesign: defineTable({
    singleton: v.string(),
    themeId: v.union(v.literal("clinical-grid"), v.literal("midnight-lab"), v.literal("molecule-editorial"), v.literal("cold-chain"), v.literal("biofuture")),
    primaryColor: v.string(),
    accentColor: v.string(),
    surfaceColor: v.string(),
    textColor: v.string(),
    headingFont: v.string(),
    bodyFont: v.string(),
    updatedAt: v.number(),
  }).index("by_singleton", ["singleton"]),
  pageSections: defineTable({
    sectionId: v.string(),
    type: v.union(v.literal("hero"), v.literal("featured"), v.literal("trust"), v.literal("categories"), v.literal("certificates"), v.literal("editorial"), v.literal("newsletter")),
    title: v.string(),
    subtitle: v.string(),
    enabled: v.boolean(),
    sortOrder: v.number(),
    updatedAt: v.number(),
  }).index("by_sort_order", ["sortOrder"]).index("by_section_id", ["sectionId"]),
  pages: defineTable({
    slug: v.string(),
    title: v.string(),
    pageType: v.union(v.literal("custom"), v.literal("legal")),
    status: v.union(v.literal("draft"), v.literal("published")),
    content: v.string(),
    showInHeader: v.boolean(),
    showInFooter: v.boolean(),
    seoTitle: v.optional(v.string()),
    seoDescription: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_status", ["status"]),
  shippingMethods: defineTable({
    name: v.string(),
    description: v.string(),
    price: v.number(),
    estimatedDays: v.string(),
    enabled: v.boolean(),
    sortOrder: v.number(),
    freeAbove: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_enabled_and_sort_order", ["enabled", "sortOrder"]),
  paymentSettings: defineTable({
    singleton: v.string(),
    provider: v.union(v.literal("stripe"), v.literal("manual")),
    currency: v.string(),
    enabled: v.boolean(),
    statementDescriptor: v.string(),
    checkoutMessage: v.string(),
    updatedAt: v.number(),
  }).index("by_singleton", ["singleton"]),
});
