import Image from "next/image";
import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import { StoreLayout } from "@/components/store-shell";
import { products } from "@/lib/catalog";

export default function Home() {
  return <StoreLayout><main>
    <section className="hero"><div className="container hero__grid"><div className="hero__copy"><span className="pill">Documentation-first research supply</span><h1>Research<br />compounds,<br />labeled with<br />clarity.</h1><p>Browse a focused catalog of lyophilized research compounds with variant-level labeling and accessible batch documentation.</p><div className="hero__actions"><Link className="button button--primary" href="/shop">Shop compounds</Link><Link className="button button--white" href="/lab-results">View batch COAs</Link></div><div className="hero__proof"><span>✓ 24 current research SKUs</span><span>✓ 32 hosted certificates</span><span>✓ Free U.S. shipping at $100+</span></div></div><div className="hero__visual"><div className="hero-ring" /><Image className="hero-vial hero-vial--rear" src="/assets/hero/retatrutide-20mg.png" width={390} height={670} alt="Retatrutide 20mg Axispep vial" priority /><Image className="hero-vial hero-vial--front" src="/assets/hero/tesamorelin-10mg.png" width={430} height={760} alt="Tesamorelin 10mg Axispep vial" priority /><div className="research-seal"><small>AXISPEP</small><strong>RESEARCH</strong><small>USE ONLY</small></div></div></div></section>
    <section className="section catalogue-section"><div className="container"><div className="section-heading centered"><span className="eyebrow eyebrow--blue">Current catalogue</span><h2>Axispep bestsellers</h2><p>Grouped by compound, with strength-specific pricing, SKUs, and bottle labels.</p></div><div className="product-grid">{products.slice(0, 8).map((product) => <ProductCard product={product} key={product.slug} />)}</div><div className="centered section-cta"><Link href="/shop" className="button button--outline">View all 12 compounds</Link></div></div></section>
    <section className="section workflow-section"><div className="container"><div className="section-heading"><span className="eyebrow eyebrow--blue">Built for bench workflows</span><h2>Simple sourcing, clear<br />records.</h2></div><div className="feature-grid">{[["01", "Variant-level labels", "Every strength has its own SKU, price, and matching product image."], ["02", "Batch library", "Search compounds and lot numbers, then open the hosted certificate PDF."], ["03", "Research-only positioning", "Clear use limitations appear throughout product, cart, and checkout surfaces."], ["04", "Operational back office", "Catalog, stock, orders, customers, discounts, and certificates stay in one place."]].map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section certificates-section"><div className="container certificates-grid"><div><span className="eyebrow">Batch documentation</span><h2>A certificate<br />library designed<br />to be checked.</h2><p>Search all hosted batch records by compound or batch number before beginning research.</p><Link className="button button--white" href="/lab-results">Browse 32 certificates</Link></div><div className="certificate-stats"><div><strong>32</strong><span>Hosted PDFs</span></div><div><strong>24</strong><span>Current SKUs</span></div><div><strong>12</strong><span>Compound pages</span></div></div></div></section>
    <section className="section final-cta"><div className="container"><div><span className="eyebrow eyebrow--blue">Axispep research</span><h2>Build a documented research order.</h2><p>A clearer checkout and complete order trail from cart to fulfillment.</p><Link href="/shop" className="button button--primary">Explore catalogue</Link></div></div></section>
  </main></StoreLayout>;
}
