"use client";

import Image from "next/image";
import Link from "next/link";
import { useMutation, useQuery } from "convex/react";
import { useAuthActions } from "@convex-dev/auth/react";
import { useState } from "react";
import { api } from "../../convex/_generated/api";
import type { Doc, Id } from "../../convex/_generated/dataModel";
import { Activity, BadgePercent, Boxes, Brush, ChevronRight, ClipboardCheck, CreditCard, FileText, FlaskConical, LayoutDashboard, Menu, PackageSearch, PanelsTopLeft, Palette, Search, ShoppingCart, Store, Truck, UserRound, Users, X } from "lucide-react";
import { money } from "@/lib/catalog";
import { TrimPathVial } from "@/components/trimpath-vial";
import { peptideThemes, type PeptideThemeId } from "@/lib/store-design";

type View = "overview" | "products" | "orders" | "customers" | "designs" | "sections" | "branding" | "pages" | "store" | "shipping" | "payments" | "account" | "discounts" | "batches";
const nav: Array<[View, string, typeof LayoutDashboard]> = [["overview", "Dashboard", LayoutDashboard], ["orders", "Orders", ShoppingCart], ["products", "Products", Boxes], ["customers", "Customers", Users], ["designs", "Designs", Palette], ["sections", "Page sections", PanelsTopLeft], ["branding", "Branding", Brush], ["pages", "Pages", FileText], ["store", "Store settings", Store], ["shipping", "Shipping", Truck], ["payments", "Payments", CreditCard], ["account", "Account", UserRound], ["discounts", "Discounts", BadgePercent], ["batches", "Batch certificates", FlaskConical]];
const orderDate = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });

export function AdminDashboard() {
  const { signOut } = useAuthActions();
  const [view, setView] = useState<View>("overview");
  const [sidebar, setSidebar] = useState(false);
  const products = useQuery(api.catalog.list);
  const orders = useQuery(api.orders.list);
  const customers = useQuery(api.admin.customers);
  const discounts = useQuery(api.admin.discounts);
  const batches = useQuery(api.admin.batches);
  const overview = useQuery(api.dashboard.overview);
  const seed = useMutation(api.seed.run);
  const updateStatus = useMutation(api.orders.updateStatus);

  const selectView = (next: View) => { setView(next); setSidebar(false); };
  const currentLabel = nav.find(([id]) => id === view)?.[1];
  return <div className="admin-shell"><aside className={`admin-sidebar ${sidebar ? "is-open" : ""}`}><div className="admin-brand"><Image src="/assets/brand/trimpath-wordmark.svg" width={234} height={38} alt="Trim Path Rx" /><span>OPERATIONS</span><button type="button" onClick={() => setSidebar(false)} aria-label="Close navigation"><X /></button></div><nav>{nav.map(([id, label, Icon]) => <button type="button" className={view === id ? "is-active" : ""} onClick={() => selectView(id)} key={id}><Icon />{label}<ChevronRight /></button>)}</nav><div className="admin-sidebar__foot"><Link href="/">View storefront</Link><span>Convex operational console</span></div></aside><div className="admin-overlay" onClick={() => setSidebar(false)} />
    <div className="admin-main"><header className="admin-topbar"><div><button type="button" className="admin-menu" onClick={() => setSidebar(true)}><Menu /></button><span>{currentLabel}</span></div><label><Search /><input placeholder="Search operations" /></label><div className="environment"><span /> Trim Path Rx Cloud</div><button type="button" className="admin-signout" onClick={() => void signOut()}>Sign out</button></header><main className="admin-content">
      {!products?.length && <section className="seed-banner"><div><ClipboardCheck /><span><strong>Initialize the Trim Path Rx catalogue</strong>Seed 12 products, 24 variants, store settings, and a starter discount.</span></div><button type="button" onClick={() => seed()}>Seed Convex data</button></section>}
      {view === "overview" && <><div className="admin-heading"><div><span className="admin-kicker">Live operations</span><h1>Good afternoon, Matt.</h1><p>Here is what is happening across Trim Path Rx today.</p></div><button type="button" className="admin-primary" onClick={() => setView("orders")}>Review orders</button></div><div className="stat-grid">{[["Gross revenue", money(overview?.revenue || 0), "+12.4%", Activity], ["Orders", String(overview?.orders || 0), "All time", ShoppingCart], ["Customers", String(overview?.customers || 0), "Unique buyers", Users], ["Low stock", String(overview?.lowStock || 0), "Needs attention", PackageSearch]].map(([label, value, hint, Icon]) => <article key={String(label)}><div><span>{label as string}</span><Icon /></div><strong>{value as string}</strong><small>{hint as string}</small></article>)}</div><section className="admin-panel"><div className="panel-heading"><div><h2>Recent orders</h2><p>Latest customer activity across the store.</p></div><button type="button" onClick={() => setView("orders")}>View all</button></div><OrderTable orders={overview?.recentOrders || []} onStatus={updateStatus} /></section></>}
      {view === "products" && <ProductManager products={products || []} />}
      {view === "orders" && <section className="admin-panel"><div className="panel-heading"><div><h1>Orders</h1><p>Track payment, fulfillment, cancellations, and refunds.</p></div><span>{orders?.length || 0} total</span></div><OrderTable orders={orders || []} onStatus={updateStatus} /></section>}
      {view === "customers" && <section className="admin-panel"><div className="panel-heading"><div><h1>Customers</h1><p>Buyer history and lifetime value in one view.</p></div></div><div className="customer-grid">{customers?.map((customer) => <article key={customer._id}><div className="avatar">{customer.firstName[0]}{customer.lastName[0]}</div><div><strong>{customer.firstName} {customer.lastName}</strong><span>{customer.email}</span></div><div><strong>{customer.orderCount}</strong><span>orders</span></div><div><strong>{money(customer.lifetimeValue)}</strong><span>lifetime value</span></div></article>)}</div></section>}
      {view === "discounts" && <section className="admin-panel"><div className="panel-heading"><div><h1>Discounts</h1><p>Promotions with usage and availability controls.</p></div></div><div className="discount-grid">{discounts?.map((discount) => <article key={discount._id}><BadgePercent /><div><strong>{discount.code}</strong><span>{discount.type === "percent" ? `${discount.amount}% off` : `${money(discount.amount)} off`}</span></div><div><strong>{discount.usageCount}</strong><span>uses</span></div><b className={discount.active ? "status status--active" : "status"}>{discount.active ? "Active" : "Inactive"}</b></article>)}</div></section>}
      {view === "batches" && <section className="admin-panel"><div className="panel-heading"><div><h1>Batch certificates</h1><p>Publish searchable compound and lot documentation.</p></div><span>{batches?.length || 0} records</span></div>{!batches?.length ? <div className="admin-empty"><FlaskConical /><h3>No certificates yet</h3><p>Add lot records and hosted PDF links before publishing the library.</p></div> : <div>{batches.map((batch) => <article key={batch._id}>{batch.compound} {batch.lotNumber}</article>)}</div>}</section>}
      {["designs","sections","branding","pages","store","shipping","payments","account"].includes(view) && <CommerceManager view={view} />}
    </main></div>
  </div>;
}

function ProductManager({ products }: { products: Array<Doc<"products">> }) {
  const updateInventory = useMutation(api.catalog.updateInventory); const toggleActive = useMutation(api.catalog.toggleActive); const saveProduct = useMutation(api.catalog.save); const [editing, setEditing] = useState<Doc<"products"> | "new" | null>(null); const current = editing === "new" ? null : editing;
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const count = Math.max(1, Number(f.get("variantCount"))); const variants = Array.from({ length: count }, (_, index) => ({ sku: String(f.get(`sku-${index}`)), strength: String(f.get(`strength-${index}`)), price: Number(f.get(`price-${index}`)), inventory: Number(f.get(`inventory-${index}`)), lowStockAt: Number(f.get(`lowStockAt-${index}`)), active: f.get(`active-${index}`) === "on" })); const values = { ...(current ? { productId: current._id } : {}), slug: String(f.get("slug")), name: String(f.get("name")), category: String(f.get("category")) as "GLP-1"|"Peptides", description: String(f.get("description")), image: String(f.get("image")), badge: String(f.get("badge")), featured: f.get("featured") === "on", tags: String(f.get("tags")).split(",").map((item) => item.trim()).filter(Boolean), seoTitle: String(f.get("seoTitle")), seoDescription: String(f.get("seoDescription")), sortOrder: Number(f.get("sortOrder")), active: f.get("active") === "on", variants }; void saveProduct(values).then(() => setEditing(null)); }
  return <section className="admin-panel"><div className="panel-heading"><div><h1>Products & inventory</h1><p>Create products, manage variant prices and stock, and publish directly to the storefront.</p></div><button type="button" className="admin-primary" onClick={() => setEditing("new")}>Add product</button></div>
    {editing && <form className="product-editor" onSubmit={submit}><div className="product-editor__title"><div><span className="admin-kicker">Catalog editor</span><h2>{current ? `Edit ${current.name}` : "Create a peptide product"}</h2></div><button type="button" onClick={() => setEditing(null)}>Close</button></div><div className="commerce-form product-editor__fields"><label>Product name<input name="name" defaultValue={current?.name || ""} required /></label><label>URL slug<input name="slug" defaultValue={current?.slug || ""} required /></label><label>Category<select name="category" defaultValue={current?.category || "Peptides"}><option>Peptides</option><option>GLP-1</option></select></label><label>Badge<input name="badge" defaultValue={current?.badge || ""} placeholder="Popular" /></label><label className="full">Description<textarea name="description" defaultValue={current?.description || ""} required /></label><label className="full">Bottle image path<input name="image" defaultValue={current?.image || "/assets/products/trimpath-vial.svg"} required /></label><label>Tags<input name="tags" defaultValue={current?.tags?.join(", ") || "research, peptide"} /></label><label>Sort order<input name="sortOrder" type="number" defaultValue={current?.sortOrder || products.length * 10 + 10} /></label><label className="full">SEO title<input aria-label="SEO title" name="seoTitle" defaultValue={current?.seoTitle || current?.name || ""} /></label><label className="full">SEO description<input aria-label="SEO description" name="seoDescription" defaultValue={current?.seoDescription || current?.description || ""} /></label><div className="full variant-editor"><h3>Variants</h3>{(current?.variants || [{ sku: "", strength: "10mg", price: 0, inventory: 0, lowStockAt: 10, active: true }]).map((variant, index) => <div key={variant.sku || "new-variant"}><label>SKU<input name={`sku-${index}`} defaultValue={variant.sku} required /></label><label>Strength<input name={`strength-${index}`} defaultValue={variant.strength} required /></label><label>Price<input name={`price-${index}`} type="number" min="0" step=".01" defaultValue={variant.price} required /></label><label>Inventory<input name={`inventory-${index}`} type="number" min="0" defaultValue={variant.inventory} /></label><label>Low-stock alert<input name={`lowStockAt-${index}`} type="number" min="0" defaultValue={variant.lowStockAt} /></label><label className="toggle"><input name={`active-${index}`} type="checkbox" defaultChecked={variant.active} /> Active</label></div>)}<input name="variantCount" type="hidden" value={current?.variants.length || 1} /></div><div className="checks full"><label><input name="active" type="checkbox" defaultChecked={current?.active ?? true} /> Published</label><label><input name="featured" type="checkbox" defaultChecked={current?.featured ?? true} /> Featured</label></div><button type="submit">Save product</button></div></form>}
    <div className="inventory-list">{products.map((product) => <article key={product._id}><TrimPathVial name={product.name} strength={product.variants[0]?.strength || ""} /><div className="inventory-product"><strong>{product.name}</strong><span>{product.category} · {product.active ? "Active" : "Hidden"}</span><div><button type="button" className="inline-action" onClick={() => setEditing(product)}>Edit product</button><button type="button" className="inline-action" onClick={() => void toggleActive({ productId: product._id, active: !product.active })}>{product.active ? "Hide" : "Publish"}</button></div></div><div className="variant-stock">{product.variants.map((variant) => <label key={variant.sku}><span><strong>{variant.strength} · {money(variant.price)}</strong>{variant.sku}</span><input type="number" min="0" defaultValue={variant.inventory} onBlur={(event) => { const inventory = event.currentTarget.valueAsNumber; if (Number.isFinite(inventory)) void updateInventory({ productId: product._id, sku: variant.sku, inventory }); }} /><small>units</small></label>)}</div></article>)}</div>
  </section>;
}

function CommerceManager({ view }: { view: View }) {
  const state = useQuery(api.commerce.adminState); const saveDesign = useMutation(api.commerce.saveDesign); const saveSection = useMutation(api.commerce.saveSection); const savePage = useMutation(api.commerce.savePage); const saveStoreSettings = useMutation(api.commerce.saveStoreSettings); const saveShippingMethod = useMutation(api.commerce.saveShippingMethod); const savePaymentSettings = useMutation(api.commerce.savePaymentSettings); const saveAccount = useMutation(api.commerce.saveAccount);
  const [saved, setSaved] = useState(""); const settings = { storeName: "Trim Path Rx", legalName: "Trim Path Rx, LLC", supportEmail: "", supportPhone: "800-637-9046", storeTagline: "Documentation-first research supply", contactAddress: "", announcement: "Free U.S. shipping on qualifying $100+ research orders", minimumOrder: 100, freeShippingThreshold: 100, checkoutEnabled: false, currency: "USD", timezone: "America/New_York", metaTitle: "Trim Path Rx research compounds", metaDescription: "Documentation-first peptide research compounds.", logoUrl: "/assets/brand/trimpath-wordmark.svg", darkLogoUrl: "", faviconUrl: "", ...state?.settings };
  const done = (message: string) => { setSaved(message); window.setTimeout(() => setSaved(""), 2600); };
  const saveStore = async (changes: Partial<typeof settings>) => { const next = { ...settings, ...changes }; await saveStoreSettings({ storeName: next.storeName, legalName: next.legalName, supportEmail: next.supportEmail, supportPhone: next.supportPhone, storeTagline: next.storeTagline, contactAddress: next.contactAddress, announcement: next.announcement, minimumOrder: Number(next.minimumOrder), freeShippingThreshold: Number(next.freeShippingThreshold), checkoutEnabled: Boolean(next.checkoutEnabled), currency: next.currency, timezone: next.timezone, metaTitle: next.metaTitle, metaDescription: next.metaDescription, logoUrl: next.logoUrl, darkLogoUrl: next.darkLogoUrl, faviconUrl: next.faviconUrl }); done("Storefront updated"); };
  if (!state) return <section className="admin-panel"><div className="admin-empty">Loading commerce settings…</div></section>;
  return <section className="admin-panel commerce-panel"><div className="panel-heading"><div><h1>{nav.find(([id]) => id === view)?.[1]}</h1><p>Changes publish to the connected storefront data model.</p></div>{saved && <span className="save-confirmation">✓ {saved}</span>}</div>
    {view === "designs" && <div className="theme-grid">{peptideThemes.map((theme) => <article className={state.design?.themeId === theme.id ? "is-selected" : ""} key={theme.id}><div className="theme-preview" style={{ background: `linear-gradient(145deg, ${theme.colors[2]} 55%, ${theme.colors[0]} 55%)` }}><i style={{ background: theme.colors[1] }} /><b style={{ color: theme.colors[3] }}>PEPTIDE<br />RESEARCH</b></div><h3>{theme.name}</h3><p>{theme.description}</p><div className="swatches">{theme.colors.map((color) => <span style={{ background: color }} key={color} />)}</div><button type="button" onClick={() => void saveDesign({ themeId: theme.id as PeptideThemeId, primaryColor: theme.colors[0], accentColor: theme.colors[1], surfaceColor: theme.colors[2], textColor: theme.colors[3], headingFont: "Manrope", bodyFont: "Manrope" }).then(() => done(`${theme.name} applied`))}>{state.design?.themeId === theme.id ? "Selected" : "Use this design"}</button></article>)}</div>}
    {view === "sections" && <div className="editor-list">{state.sections.map((section: { sectionId: string; type: "hero"|"featured"|"trust"|"categories"|"certificates"|"editorial"|"newsletter"; title: string; subtitle: string; enabled: boolean; sortOrder: number }) => <form key={section.sectionId} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void saveSection({ sectionId: section.sectionId, type: section.type, title: String(form.get("title")), subtitle: String(form.get("subtitle")), enabled: form.get("enabled") === "on", sortOrder: Number(form.get("sortOrder")) }).then(() => done("Section saved")); }}><div className="editor-list__head"><strong>{section.type}</strong><label><input name="enabled" type="checkbox" defaultChecked={section.enabled} /> Visible</label></div><label>Heading<input name="title" defaultValue={section.title} /></label><label>Description<textarea name="subtitle" defaultValue={section.subtitle} /></label><label>Position<input name="sortOrder" type="number" defaultValue={section.sortOrder} /></label><button type="submit">Save section</button></form>)}</div>}
    {view === "branding" && <form className="commerce-form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void saveStore({ storeName: String(f.get("storeName")), legalName: String(f.get("legalName")), storeTagline: String(f.get("storeTagline")), logoUrl: String(f.get("logoUrl")), darkLogoUrl: String(f.get("darkLogoUrl")), faviconUrl: String(f.get("faviconUrl")) }); }}><label>Store name<input name="storeName" defaultValue={settings.storeName} /></label><label>Legal business name<input name="legalName" defaultValue={settings.legalName} /></label><label className="full">Brand tagline<input name="storeTagline" defaultValue={settings.storeTagline} /></label><label className="full">Primary logo path or URL<input name="logoUrl" defaultValue={settings.logoUrl} /></label><label>Dark logo path or URL<input name="darkLogoUrl" defaultValue={settings.darkLogoUrl} /></label><label>Favicon path or URL<input name="faviconUrl" defaultValue={settings.faviconUrl} /></label><button type="submit">Save branding</button></form>}
    {view === "pages" && <div className="editor-list pages-editor">{[...state.pages, { slug: "", title: "", pageType: "custom", status: "draft", content: "", showInHeader: false, showInFooter: true, seoTitle: "", seoDescription: "" }].map((page) => <form key={"_id" in page ? page._id : "new-page"} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void savePage({ slug: String(f.get("slug")), title: String(f.get("title")), pageType: String(f.get("pageType")) as "custom"|"legal", status: String(f.get("status")) as "draft"|"published", content: String(f.get("content")), showInHeader: f.get("showInHeader") === "on", showInFooter: f.get("showInFooter") === "on", seoTitle: String(f.get("seoTitle")), seoDescription: String(f.get("seoDescription")) }).then(() => done("Page saved")); }}><div className="editor-list__head"><strong>{page.title || "Create a page"}</strong><span>{page.status}</span></div><label>Title<input name="title" defaultValue={page.title} required /></label><label>URL slug<input name="slug" defaultValue={page.slug} required /></label><div className="split"><label>Type<select name="pageType" defaultValue={page.pageType}><option value="custom">Custom</option><option value="legal">Legal</option></select></label><label>Status<select name="status" defaultValue={page.status}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><label>Content<textarea name="content" defaultValue={page.content} rows={7} /></label><div className="checks"><label><input name="showInHeader" type="checkbox" defaultChecked={page.showInHeader} /> Header</label><label><input name="showInFooter" type="checkbox" defaultChecked={page.showInFooter} /> Footer</label></div><input aria-label="SEO title" name="seoTitle" defaultValue={page.seoTitle} placeholder="SEO title" /><input aria-label="SEO description" name="seoDescription" defaultValue={page.seoDescription} placeholder="SEO description" /><button type="submit">{page.slug ? "Update page" : "Create page"}</button></form>)}</div>}
    {view === "store" && <form className="commerce-form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void saveStore({ supportEmail: String(f.get("supportEmail")), supportPhone: String(f.get("supportPhone")), contactAddress: String(f.get("contactAddress")), announcement: String(f.get("announcement")), minimumOrder: Number(f.get("minimumOrder")), freeShippingThreshold: Number(f.get("freeShippingThreshold")), checkoutEnabled: f.get("checkoutEnabled") === "on", currency: String(f.get("currency")), timezone: String(f.get("timezone")), metaTitle: String(f.get("metaTitle")), metaDescription: String(f.get("metaDescription")) }); }}><label>Support email<input name="supportEmail" type="email" defaultValue={settings.supportEmail} /></label><label>Support phone<input name="supportPhone" defaultValue={settings.supportPhone} /></label><label className="full">Contact address<textarea name="contactAddress" defaultValue={settings.contactAddress} /></label><label className="full">Announcement bar<input name="announcement" defaultValue={settings.announcement} /></label><label>Minimum order<input name="minimumOrder" type="number" min="0" step=".01" defaultValue={settings.minimumOrder} /></label><label>Free shipping threshold<input name="freeShippingThreshold" type="number" min="0" step=".01" defaultValue={settings.freeShippingThreshold} /></label><label>Currency<input name="currency" defaultValue={settings.currency} /></label><label>Timezone<input name="timezone" defaultValue={settings.timezone} /></label><label className="full">SEO title<input name="metaTitle" defaultValue={settings.metaTitle} /></label><label className="full">SEO description<textarea name="metaDescription" defaultValue={settings.metaDescription} /></label><label className="toggle"><input name="checkoutEnabled" type="checkbox" defaultChecked={settings.checkoutEnabled} /> Accept orders on the storefront</label><button type="submit">Save store settings</button></form>}
    {view === "shipping" && <div className="editor-list">{[...state.shippingMethods, { _id: null, name: "", description: "", price: 0, estimatedDays: "2–5 business days", enabled: true, sortOrder: 20, freeAbove: settings.freeShippingThreshold }].map((method) => <form key={(method._id ?? method.name) || "new-shipping"} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void saveShippingMethod({ ...(method._id ? { id: method._id } : {}), name: String(f.get("name")), description: String(f.get("description")), price: Number(f.get("price")), estimatedDays: String(f.get("estimatedDays")), enabled: f.get("enabled") === "on", sortOrder: Number(f.get("sortOrder")), freeAbove: Number(f.get("freeAbove")) }).then(() => done("Shipping method saved")); }}><div className="editor-list__head"><strong>{method.name || "Add shipping method"}</strong><label><input name="enabled" type="checkbox" defaultChecked={method.enabled} /> Enabled</label></div><label>Name<input name="name" defaultValue={method.name} required /></label><label>Description<input name="description" defaultValue={method.description} /></label><div className="split"><label>Price<input name="price" type="number" step=".01" min="0" defaultValue={method.price} /></label><label>Free above<input name="freeAbove" type="number" step=".01" min="0" defaultValue={method.freeAbove} /></label></div><label>Delivery estimate<input name="estimatedDays" defaultValue={method.estimatedDays} /></label><input name="sortOrder" type="hidden" value={method.sortOrder} /><button type="submit">{method._id ? "Update method" : "Add method"}</button></form>)}</div>}
    {view === "payments" && <form className="commerce-form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void savePaymentSettings({ provider: String(f.get("provider")) as "stripe"|"manual", currency: String(f.get("currency")), enabled: f.get("enabled") === "on", statementDescriptor: String(f.get("statementDescriptor")), checkoutMessage: String(f.get("checkoutMessage")) }).then(() => done("Payment settings saved")); }}><label>Provider<select name="provider" defaultValue={state.payment?.provider || "stripe"}><option value="stripe">Stripe Checkout</option><option value="manual">Manual payment</option></select></label><label>Currency<input name="currency" defaultValue={state.payment?.currency || "USD"} /></label><label>Statement descriptor<input name="statementDescriptor" defaultValue={state.payment?.statementDescriptor || "TRIMPATHRX"} /></label><label>Checkout message<input name="checkoutMessage" defaultValue={state.payment?.checkoutMessage || "Secure card payment"} /></label><label className="toggle"><input name="enabled" type="checkbox" defaultChecked={state.payment?.enabled || false} /> Payment provider is configured and ready</label><div className="integration-note"><CreditCard /><div><strong>Stripe server configuration</strong><p>Checkout requires STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, and ORDER_WRITE_SECRET in Vercel and Convex. Secrets are never shown in this console.</p></div></div><button type="submit">Save payment settings</button></form>}
    {view === "account" && <form className="commerce-form" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void saveAccount({ displayName: String(f.get("displayName")), phone: String(f.get("phone")), emailNotifications: f.get("emailNotifications") === "on" }).then(() => done("Account updated")); }}><label>Display name<input name="displayName" defaultValue={state.admin?.displayName || state.user?.name || "Matt"} /></label><label>Phone<input name="phone" defaultValue={state.admin?.phone || ""} /></label><label className="full">Sign-in email<input value={state.user?.email || ""} disabled readOnly /></label><label className="toggle"><input name="emailNotifications" type="checkbox" defaultChecked={state.admin?.emailNotifications ?? true} /> Email me order and low-stock updates</label><button type="submit">Save account</button></form>}
  </section>;
}

type OrderStatus = Doc<"orders">["status"];

function OrderTable({ orders, onStatus }: { orders: Array<Doc<"orders">>; onStatus: (args: { orderId: Id<"orders">; status: OrderStatus }) => Promise<unknown> }) {
  return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Items</th><th>Total</th><th>Created</th></tr></thead><tbody>{orders.map((order) => <tr key={order._id}><td data-label="Order"><strong>{order.orderNumber}</strong></td><td data-label="Customer"><strong>{order.customerName}</strong><span>{order.customerEmail}</span></td><td data-label="Status"><select value={order.status} onChange={(event) => onStatus({ orderId: order._id, status: event.target.value as OrderStatus })}><option value="pending">Pending</option><option value="paid">Paid</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select></td><td data-label="Items">{order.items.reduce((sum, item) => sum + item.quantity, 0)}</td><td data-label="Total"><strong>{money(order.total)}</strong></td><td data-label="Created">{orderDate.format(order.createdAt)}</td></tr>)}</tbody></table>{!orders.length && <div className="admin-empty"><ShoppingCart /><h3>No orders yet</h3><p>New checkout attempts will appear here.</p></div>}</div>;
}
