"use client";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { ProductCard } from "@/components/product-card";
import { StoreLayout } from "@/components/store-shell";
import { TrimPathVial } from "@/components/trimpath-vial";
import { products as fallback, type Product } from "@/lib/catalog";

export function StorefrontHome() {
  const liveProducts = useQuery(api.catalog.listActive); const commerce = useQuery(api.commerce.publicStorefront); const products = (liveProducts?.length ? liveProducts : fallback) as Array<Product & { featured?: boolean }>; const sections = commerce?.sections ?? [];
  const hero = sections.find((section) => section.type === "hero" && section.enabled); const featured = sections.find((section) => section.type === "featured" && section.enabled); const trust = sections.find((section) => section.type === "trust" && section.enabled); const certificates = sections.find((section) => section.type === "certificates" && section.enabled);
  return <StoreLayout><main>
    {hero && <section className="hero"><div className="container hero__grid"><div className="hero__copy"><span className="pill">Documentation-first research supply</span><h1>{hero.title}</h1><p>{hero.subtitle}</p><div className="hero__actions"><Link className="button button--primary" href="/shop">Shop compounds</Link><Link className="button button--white" href="/lab-results">View batch COAs</Link></div><div className="hero__proof"><span>✓ {products.reduce((sum, item) => sum + item.variants.length, 0)} current research SKUs</span><span>✓ Batch-linked documentation</span><span>✓ Configurable U.S. shipping</span></div></div><div className="hero__visual"><div className="hero-ring" /><TrimPathVial className="hero-vial hero-vial--rear" name={products[0]?.name ?? "Retatrutide"} strength={products[0]?.variants[0]?.strength ?? "20mg"} /><TrimPathVial className="hero-vial hero-vial--front" name={products[1]?.name ?? "Tesamorelin"} strength={products[1]?.variants[0]?.strength ?? "10mg"} /><div className="research-seal"><small>TRIM PATH RX</small><strong>RESEARCH</strong><small>USE ONLY</small></div></div></div></section>}
    {featured && <section className="section catalogue-section"><div className="container"><div className="section-heading centered"><span className="eyebrow eyebrow--blue">Current catalogue</span><h2>{featured.title}</h2><p>{featured.subtitle}</p></div><div className="product-grid">{products.filter((item) => item.featured !== false).slice(0, 8).map((product) => <ProductCard product={product} key={product.slug} />)}</div><div className="centered section-cta"><Link href="/shop" className="button button--outline">View all {products.length} compounds</Link></div></div></section>}
    {trust && <section className="section workflow-section"><div className="container"><div className="section-heading"><span className="eyebrow eyebrow--blue">Peptide commerce, connected</span><h2>{trust.title}</h2><p>{trust.subtitle}</p></div><div className="feature-grid">{[["01","Live product catalog","Products, variants, prices, stock, and availability flow directly from the back office."],["02","Canonical checkout","Every price is recalculated from Convex before Stripe checkout is created."],["03","Batch documentation","Certificates stay searchable by compound and lot number."],["04","Fulfillment controls","Shipping choices, payment state, customers, and order status share one operational record."]].map(([number,title,copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>}
    {certificates && <section className="section certificates-section"><div className="container certificates-grid"><div><span className="eyebrow">Batch documentation</span><h2>{certificates.title}</h2><p>{certificates.subtitle}</p><Link className="button button--white" href="/lab-results">Browse certificates</Link></div><div className="certificate-stats"><div><strong>{products.length}</strong><span>Compounds</span></div><div><strong>{products.reduce((sum,item)=>sum+item.variants.length,0)}</strong><span>Current SKUs</span></div><div><strong>1</strong><span>Connected catalog</span></div></div></div></section>}
  </main></StoreLayout>;
}
